run:
  deadline: 1m
  issues-exit-code: 1
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

# crypto/rand vs math/rand is no difference here.
issues:
  exclude-rules:
    - path: iter/
      text: "weak random"
      linters:
        gosec

linters:
  enable-all: true
  disable:
    - funlen
    - gochecknoglobals
    - lll
    - maligned
    - nlreturn
    - wsl
  fast: false
